# 配置模式
setup-mode: false

# 房间单位，需要整除此数
unit-size: 7
unit-margin: 1

default-road: "road"

# 地图名称
slime-world:
  id: "Dungeon"
  difficulty: "normal"
  spawn-x: 0
  spawn-y: 80
  spawn-z: 0
  spawn-yaw: 0
  allow-animals: false
  allow-monsters: false
  dragon-battle: false
  pvp: false
  environment: "normal"
  world-type: "DEFAULT"
  default-biome: "minecraft:plains"
# 镜像世界 ID
mirror-world-id: "DungeonMirror-%timestamp%"

# 地图数据库
slime-database:
  host: mysql.ipv4.yistars.net
  port: 3306
  username: GameMap
  password: 8RjhGeW2w57GYCEP
  database: gamemap
  use-ssl: false
  sql-url: jdbc:mysql://{host}:{port}/{database}?autoReconnect=true&allowMultiQueries=true&useSSL={usessl}

# 纯路径地图生成配置
path-only:
  # 矩形半径，尽量为偶数
  grid-radius: 18
  # step1. 随机移除网格中的非交叉点的概率，取值范围 [0,1]
  random-remove-point-probability: 0.125
  # step2-1. 随机移除矩形区域的个数
  random-remove-rectangle-min: 24 # 最小值
  random-remove-rectangle-range: 24 # 最小值额外的随机个数最大值
  # step2-1. 随机移除矩形区域的边长
  random-remove-rectangle-sizes: [ -3, -1, 1, 3 ] # 边长的范围，尽量为奇数
  # step2-2. 随机移除靠边缘的矩形区域的个数
  random-remove-edge-rectangle-min: 12 # 最小值
  random-remove-edge-rectangle-range: 12 # 最小值额外的随机个数最大值
  # step2-2. 随机移除靠边缘的矩形区域的边长
  random-remove-edge-rectangle-sizes: [ 1, 3, 5 ] # 边长的范围，尽量为奇数